
title: Asifali Shaik | Portfolio
email: asifali.shaik@asiftechhub.com
description: >-
  DevOps Engineer | Cloud Enthusiast | Blogger
baseurl: "" 
url: "https://allahasif48.github.io/asiftechhub"  # Your GitHub Pages URL
theme: minima
plugins:
  - jekyll-feed

# Navigation menu
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "Blog"
    url: "/blog"
  - title: "Contact"
    url: "/contact"
  - title: "Resume"
    url: "/resume"

# Social Media Links (optional)
social:
  github: "https://github.com/allahasif48"
  linkedin: "https://www.linkedin.com/in/asifali-shaik"
  twitter: "https://twitter.com/asifali_tech"

# Customizing Minima theme (optional)
minima:
  # You can add a custom logo here
  logo: "/assets/images/logo.png"
  
# Exclude unnecessary files from being copied to the site
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - Gemfile.lock
